// Liste des pays (français) — priorité Afrique de l'Ouest
export const Country = [
  "Côte d'Ivoire",
  "Bénin",
  "Burkina Faso",
  "Cameroun",
  "Cap-Vert",
  "Centrafrique",
  "Comores",
  "Congo",
  "RD Congo",
  "Gabon",
  "Gambie",
  "Ghana",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Liberia",
  "Mali",
  "Mauritanie",
  "Niger",
  "Nigeria",
  "Sénégal",
  "Sierra Leone",
  "Tchad",
  "Togo",
  "Algérie",
  "Maroc",
  "Tunisie",
  "France",
  "Belgique",
  "Suisse",
  "Canada",
  "Autre pays",
];
